spring:
  profiles:
    active: local # default로 사용될 프로파일 명시
    include: key # 분리되어 있는 yml 포함

--- # 프로파일을 구분

spring:
  config:
    activate:
      on-profile: local # 해당 프로파일이 선택되었을 때만 활성화

---

spring:
  config:
    activate:
      on-profile: test